version: '3'

services:
  client:
    build: .
#    restart: always
#    network_mode: host
#    env_file:
#      - .env
    expose:
      - 3000
    ports:
      - "3000:3000"
    command:
      "npm run start"





